spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://fullstackspringbootdb.c92ubmxps6dm.ap-southeast-2.rds.amazonaws.com:5432/amigoscodedemo
    username: amigoscode
    password: 123456789
    pool-size: 30